var color1 = ["#dae9f4", "#7f9eb2", "#77919d", "#274c5e"];
d3.select("#color1")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color1)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color1[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color1[i];})


var color2 = ["#ffeb3b", "#fdd835", "#fbbc00", "#ffa000", "#ef6c00", "#d84315"];
d3.select("#color2")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color2)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color2[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color2[i];})


var color3 = ["#b2ebf2", "#4dd0e1", "#00bcd4", "#00acc1", "#0097a7", "#006064"];
d3.select("#color3")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color3)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color3[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color3[i];})

var color4 = ["#cff09e", "#a8dba8", "#79bd9a", "#3b8686"];
d3.select("#color4")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color4)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color4[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color4[i];})

var color5 = ["#f0f4c3", "#dce775", "#aed581", "#8bc34a", "#689f38", "#388e3c", "#1b5e20"];
d3.select("#color5")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color5)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color5[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color5[i];})

var color6 = ["#b2ebf2", "#4fc3f7", "#1565c0", "#283593"];
d3.select("#color6")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color6)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color6[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color6[i];})


var color7 = ["#b2ebf2", "#008c9e", "#005f6b", "#343838"];
d3.select("#color7")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color7)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color7[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color7[i];})


var color8 = ["#b2ebf2", "#4dd0e1", "#0097a7", "#006064"];
d3.select("#color8")
    .append("svg")
        .attr("width", 2000)
        .attr("height", 80)
    .selectAll("rect")
    .data(color8)
    .enter()
    .append("rect")
        .attr("width", 80)
        .attr("height", 20)
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 50)
        .attr("fill", function(d, i) {return color8[i];})
    .append("text")
        .attr("x", function(d,i) {return i*100 + 20;})
        .attr("y", 0)
        .text(function(d, i) {return color8[i];})


